import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import BottomNav from "@/components/BottomNav";
import { ThirdwebProvider } from "thirdweb/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "relative font-sans antialiased h-full max-w-xl mx-auto",
          inter.className
        )}
      >
        <main className="relative flex flex-col">
          <div className="flex-grow flex-1 pb-[76.8px]">
            <ThirdwebProvider>{children}</ThirdwebProvider>
          </div>
        </main>
        <BottomNav />
      </body>
    </html>
  );
}
